baseURL = "https://blackdesertdog.com/"
languageCode = "en-us"
title = "Black Desert Dog"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = false
  showToc = false
  showBreadCrumbs = false
  showCodeCopyButtons = true
  favicon = "favicon.ico"

[[menu.main]]
  identifier = "reading-log"
  name = "Reading Log"
  url = "/reading-log/"
  weight = 10

[params.homeInfoParams]
# Leave this section out to skip homepage message entirely

