baseURL = "https://blackdesertdog.com/"
languageCode = "en-us"
title = "Black Desert Dog"
theme = "PaperMod"

[params]
defaultTheme = "light"
showReadingTime = true
showToc = false
showBreadCrumbs = false
showCodeCopyButtons = true
favicon = "favicon.ico"

[params.homeInfoParams]
# Leave this section out to skip homepage message entirely

